icdocsoc/emails

markdown/2017-10-02-welcome.md

Welcome 2017 Draft

---

markdown/2017-10-16.md

Digest for 2017-10-16.
[Draft 1 PDF](https://github.com/icdocsoc/emails/files/1385613/2017-10-16.D1.pdf)

[SENT 16/10/17] Digest

---

markdown/2017-10-23.md

[Preview Draft 1](https://github.com/icdocsoc/emails/files/1407093/draft1.pdf)
Please review thanx

[SENT 23/10/17] Digest

---

markdown/2017-10-30.md

[SENT 30/10/17] Digest

---

markdown/2017-11-06.md

[SENT 06/11/17] Digest

---

markdown/2017-11-13.md

[SENT 13/11/17] Digest

---

markdown/2017-11-27.md

Review pls
[predigest1.pdf](https://github.com/icdocsoc/emails/files/1507801/predigest1.pdf)

[SENT 27/11/17] Digest

---

markdown/2017-12-04.md

Digest for this week.
[First Draft PDF](https://github.com/icdocsoc/emails/files/1528489/draft1.pdf)

[SENT 04/12/17] Digest

---

markdown/2017-12-11.md

review pls
[draft.pdf](https://github.com/icdocsoc/emails/files/1549899/draft.pdf)

[SENT 11/12/17] Digest

---

xml/2018-01-15.xml

Feedback please 🙂
[Digest.pdf](https://github.com/icdocsoc/emails/files/1633109/Digest.pdf)
[Digest.eml.txt](https://github.com/icdocsoc/emails/files/1633110/Digest.eml.txt)
View the eml document by removing the .txt extension.

[SENT 15/01/18] Digest

---

xml/2018-01-22.xml

Feedback pl0x
[Digest.eml.txt](https://github.com/icdocsoc/emails/files/1659653/Digest.eml.txt)
[Digest.pdf](https://github.com/icdocsoc/emails/files/1659654/Digest.pdf)

[SENT 22/01/18] Digest

---

xml/2018-01-29.xml

Digest. Should be okay to send but waiting on details on further planned events. Or we skip this and just send it…
[Digest.pdf](https://github.com/icdocsoc/emails/files/1681495/Digest.pdf)

[SENT 29/01/18] Digest

---

xml/2018-02-05.xml

review ples
[digest.pdf](https://github.com/icdocsoc/emails/files/1697128/digest.pdf)

[SENT 05/02/18] Digest

---

xml/2018-02-12.xml

please review 😄 
[digest.pdf (Preview)](https://github.com/icdocsoc/emails/files/1716015/digest.pdf)

[SENT 12/02/18] Digest

---

xml/2018-02-19.xml

[SENT 19/02/18] Digest

---

xml/2018-02-26.xml

[SENT 26/02/18] Digest

---

xml/2018-06-11.xml

[digest preview.pdf](https://github.com/icdocsoc/emails/files/2087348/digest.preview.pdf)

[SENT 11/06/18] Digest

---

xml/2018-07-15-end-of-year-survey.xml

To review: [2018-07-18-member-survey.pdf](https://github.com/icdocsoc/emails/files/2194978/2018-07-18-member-survey.pdf)

2018 End of Year Survey

---

xml/2018-07-25-barbecue.xml

To review: [2018-07-25-barbecue.html.pdf](https://github.com/icdocsoc/emails/files/2229260/2018-07-25-barbecue.html.pdf)

Summer BBQ 2018

---

xml/2018-08-23.xml

For review: 
[2018-08-23.pdf](https://github.com/icdocsoc/emails/files/2315927/2018-08-23.pdf)

[SENT] Add 2018-08-23.xml

---

xml/2018-10-01.xml

Needs sign-off from:
- @alebonardi for freshers' fair details
- @alebonardi for sponsors' exhibition timing
- @martinzlocha for Liquidnet time and location (deadline: Monday morning)
- @martinzlocha for Mums & Dads lunch (i.e., time + not _Buddies' Lunch_ like last year?)
Outstanding:
[ ] Exact time of Liquidnet ACI talk

Add 2018-10-01.xml

---

xml/2018-10-07.xml

Preliminary draft (missing football league): [2018-10-07.pdf](https://github.com/icdocsoc/emails/files/2450070/2018-10-07.pdf)

Add 2018-10-07.xml

---

xml/2018-10-14.xml

Initial draft: [2018-10-14.pdf](https://github.com/icdocsoc/emails/files/2475478/2018-10-14.pdf)
Need feedback on the images which our sponsors gave. Should I remove them?
Also please let me know if there are any events missing.

Add 2018-10-14.xml

---

xml/2018-10-18-baml-discover-technology.xml
xml/2018-10-21.xml

Initial draft: [2018-10-21.pdf](https://github.com/icdocsoc/emails/files/2497569/2018-10-21.pdf)

Add 2018-10-21.xml

---

xml/2018-10-28.xml

Initial draft: [2018-10-28.pdf](https://github.com/icdocsoc/emails/files/2521235/2018-10-28.pdf)

Add 2018-10-28.xml

---

xml/2018-11-04.xml

Initial draft: [2018-11-04.pdf](https://github.com/icdocsoc/emails/files/2545357/2018-11-04.pdf)

Add 2018-11-04.xml

---

xml/2018-11-18.xml

Initial draft: [2018-11-18.pdf](https://github.com/icdocsoc/emails/files/2590306/2018-11-18.pdf)

Add 2018-11-18.xml
